server.port: 8081
app.version: '@project.version@'
spring.application.name: 'auth-service'

# Common Spring Configuration
spring:
  datasource:
    url: ${AUTH_DB_URL}
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}
  liquibase:
    change-log: classpath:db/root.changelog.xml
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

# OAuth2 Configuration for Google
spring.security.oauth2.client:
  registration:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
      scope:
        - email
        - profile

# JWT Configuration
jwt:
  secretKey: ${JWT_SECRET}
  accessTokenExpiration: 3600000    # 60 minutes
  refreshTokenExpiration: 86400000  # 24 hours

# Swagger Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html